defaults: &defaults
  database: hairtrigger_schema_test
  host: localhost
test:
  mysql2: &mysql2_defaults
    <<: *defaults
    username: root
    prepared_statements: true
  postgresql: &postgres_defaults
    <<: *defaults
    min_messages: error
  sqlite3: &sqlite_defaults
    <<: *defaults
    database: ":memory:"
github-actions:
  mysql2:
    <<: *mysql2_defaults
    host: 127.0.0.1
    password: password
    port: <%= ENV["MYSQLPORT"] || 3306 %>
    username: root
  postgresql:
    <<: *postgres_defaults
    host: 127.0.0.1
    password: password
    port: <%= ENV["PGPORT"] || 5432 %>
    username: postgres
  sqlite3:
    <<: *sqlite_defaults
